### ISSUE TITLE
Port project to Godot 4

### ISSUE THREAD

**Issue by rr13k** [gdquest-demos/godot-visual-effects#16]
Thank you very much for the tutorial provided. Do you have any plans to provide the code for the Godot4 version? Thank you again.

**Comment by catafest** [comment]
Yes! I think will be great if you come with the last version of Godot v4.2.rc1.official [ad72de508].
The previous versions of 3.x 4.0 and 4.1 are not very good .

**Comment by wannasleepforlong** [comment]
Agreed. Would be extremely helpful. Please consider

**Comment by LaraSQP** [comment]
Indeed. With 4.3 out now, it would be great to see this project updated.

**Comment by NathanLovato** [comment]
If someone would like to contribute this, it'd be most welcome. I won't have time to port Godot projects soon.

**Comment by LaraSQP** [comment]
Darn, I wish I had the skill.

But since I have your attention, thank you very, very much for doing all this and making it available to us all.
